services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.8.1
    depends_on:
      - postgres
      - mlflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      PYTHONPATH: /opt/airflow
      _PIP_ADDITIONAL_REQUIREMENTS: >
        xgboost
        scikit-learn
        pandas
        numpy
        mlflow
        evidently
        boto3
        apache-airflow-providers-amazon

    volumes:
      - ../src:/opt/airflow/src
      - ../src/dags:/opt/airflow/dags
      - ../src/plugins:/opt/airflow/plugins
      - ../src/logs:/opt/airflow/logs
      - ../output:/opt/airflow/output

    ports:
      - "8080:8080"

    command: >
      bash -c "
      airflow db init &&
      airflow users create
        --username admin
        --password admin
        --firstname admin
        --lastname admin
        --role Admin
        --email admin@example.com || true &&
      (airflow scheduler &) &&
      airflow webserver
      "

  mlflow:
    image: python:3.8-slim
    ports:
      - "5000:5000"
    volumes:
      - ../mlflow:/mlflow
    command: >
      bash -lc "
      pip install -U pip &&
      pip install mlflow &&
      mkdir -p /mlflow/artifacts &&
      mlflow server
        --host 0.0.0.0
        --port 5000
        --backend-store-uri sqlite:////mlflow/mlflow.db
        --default-artifact-root /mlflow/artifacts
      "

volumes:
  postgres-db-volume:
